workflows:
  react-native-test:
    name: React Native Test Builds
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "CodemagicTestProject2"
        XCODE_SCHEME: "CodemagicTestProject2"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      
      - name: Build Android debug APK
        script: |
          cd android
          ./gradlew assembleDebug
      
      - name: Install iOS dependencies
        script: |
          cd ios
          pod install
      
      - name: Build iOS app for simulator
        script: |
          cd ios
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - android/app/build/outputs/**/**/*.apk
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      - /tmp/xcodebuild_logs/*.log
